DROP DATABASE if exists api_rest;

CREATE DATABASE IF NOT EXISTS api_rest DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
USE api_rest;
CREATE TABLE IF NOT EXISTS listado_clientes(
		id INT AUTO_INCREMENT,
		email VARCHAR(255) NOT NULL,
		name VARCHAR(255) NOT NULL,
		city VARCHAR(255) NOT NULL,
        cel VARCHAR(255) NOT NULL,
		PRIMARY KEY (id)
)  ENGINE=INNODB;